name: webticket-fullstack

services:
  # Nginx Proxy
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - webticket-network

  # Frontend Service
  frontend:
    container_name: frontend-app
    image: vinhdn20/webticket-frontend:latest
    build:
      context: ./FE
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=/api
    # ports:
    #   - "3000:80"
    depends_on:
      - backend
    networks:
      - webticket-network

  # Backend API Service
  backend:
    container_name: backend-api
    image: vinhdn20/webticket-backend:latest
    build:
      context: ./BE/WebTicket
      dockerfile: WebTicket/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - DOTNET_EnableDiagnostics=0
    # ports:
    #   - "5000:80"
    depends_on:
      - postgres
    networks:
      - webticket-network

  # PostgreSQL Database
  postgres:
    container_name: webticket-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=WebTicket
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=
      - POSTGRES_MAX_CONNECTIONS=50
      - POSTGRES_SHARED_BUFFERS=128MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=256MB
      - POSTGRES_WORK_MEM=4MB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    #   interval: 45s
    #   timeout: 15s
    #   retries: 5
    #   start_period: 60s
    networks:
      - webticket-network

volumes:
  postgres-data:

networks:
  webticket-network:
    driver: bridge