name: webticket
services:
    api:
        container_name: webticket-api
        image: webticket-image:latest
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443
        ports:
          - "44331:443"
        volumes:
          - /etc/ssl/certs:/etc/ssl/certs:ro
          - /etc/ssl/private:/etc/ssl/private:ro
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: postgres
        image: postgres:15-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
        ports:
          - 5432:5432
        volumes:
          - postgres-data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
          interval: 10s
          timeout: 5s
          retries: 5
volumes:
  postgres-data: